// export const authErrors = {
//     INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
//     BAD_REQUEST: 'BAD_REQUEST',
//     ONLY_PERMITTION_OWNER: 'NOT_PERMITTION_YOU_ARE_NOT_THE_OWNER',
//     UNAUTHORIZED: 'UNAUTHORIZED',
// };